name: meeus
description: Dart implementations of algorithms from the book "Astronomical Algorithms, 2nd edition" by Jean Meeus.
version: 0.2.2
homepage: https://github.com/shawnlauzon/meeus

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  unit: ^1.0.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
